---
title: "Price Prediction App"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}

# 1.0 Libraries ----

# App
library(flexdashboard)
library(shiny)

# Core
library(tidyverse)
library(tidyquant)

# Visualizations
library(plotly)

# Modeling
library(parsnip)

# Database
library(odbc)
library(RSQLite)



# 2.0 Data ----
con <- dbConnect(RSQLite::SQLite(), "../00_data/bikes_database.db")
# con <- dbConnect(RSQLite::SQLite(), "00_data/bikes_database.db")
# dbListTables(con)
bikes_tbl <- tbl(con, "bikes") %>% collect()
dbDisconnect(con)

# Scripts
source("../00_scripts/02_process_data.R")
source("../00_scripts/03_make_predictions.R")

# Model
model_xgboost <- read_rds("../00_models/model_xgboost.rds")
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
textInput(inputId = "text_bike_model", label = h4("Bike Model"), value = "Jekyll Al 1 Black Inc.")

br()
hr()
br()

actionButton(inputId = "apply", label = "Apply", icon = icon(name = "play", lib = "font-awesome"))

```


Column {data-width=650}
-----------------------------------------------------------------------

```{r}
new_bike_tbl <- eventReactive(eventExpr = input$apply, valueExpr = {
  
  generate_new_bike(
    bike_model = input$text_bike_model, 
    category_1 = "Mountain", 
    category_2 = "Over Mountain", 
    frame_material = "Aluminum", 
    .ml_model = model_xgboost)
  
}, ignoreNULL = FALSE)


```


### Price Prediction vs Product Portfolio

```{r}
# renderPrint(new_bike_tbl())

output$plotly_1 <- renderPlotly({
  bind_bike_prediction(bikes_tbl, new_bike_tbl()) %>%
    plot_bike_prediction()
})

plotlyOutput("plotly_1")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Price Prediction Used These Features

```{r}
renderTable({
  new_bike_tbl() %>% format_table()
})


```


