---
title: "R Coding"
author: "Marco Zanotti"
date: "2021-2022"
output:
  pdf_document: default
  rmdformats::downcute:
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

&nbsp;  

**R Coding** is part of the 
[Coding for Data Science](https://www.unimi.it/it/corsi/insegnamenti-dei-corsi-di-laurea/2022/coding-data-science-and-data-management)
course.  
The course aims at providing technical skills about coding/scripting aspects 
for data analysis and to manage persistent data storage of sources and results 
involved in analysis. On the one side, the Python programming language and 
the R framework are illustrated. The goal is to deal with essential notions 
about data structures and control structures of both Python and R. On the 
other side, the goal is to present the core notions of relational databases, 
such as keys, integrity, and primary/foreign key constraints, as well as the 
SQL language for data definition, manipulation, and query. Recent and 
innovative NoSQL solutions are also discussed, with special focus on a 
document-oriented system called MongoDB.   


## Course Structure

The **R Coding** part of the course aims at teaching **R Programming**.  
The state-of-the-art and modern R packages are presented from a very practical 
point of view, throughout R tutorials on each main topic. 

* 10 hours: practical lectures on the main contents  


## Contents

* Tidyverse Basics  
* Tidyverse Wrangling  
* Tidyverse Visualization  
* Tidyverse Functional Programming  
* RMarkdown  
* Flexdashboard & Shiny Basics  
* Flexdashboard Intermediate  


\pagebreak


## Evaluation

Students...


## Duration & Calendar

The course is divided into 5 lectures (2 hours each).

1. Monday 2022-02-xx, 9.00 - 11.00
2. Monday 2022-02-xx, 9.00 - 11.00
3. Monday 2022-02-xx, 9.00 - 11.00
4. Monday 2022-03-xx, 9.00 - 11.00
5. Monday 2022-03-xx, 9.00 - 11.00

Lectures take place at University of Milan, Via Conservatorio 7.   


## Requirements

Requirements:

* Lecture 0 - Introduction to R


For more information about the course contact zanottimarco17@gmail.com
or look at the 
[Course Syllabus](https://marcozanotti.github.io/rcoding-course/general-infos/rcod_syllabus.html)
